# GH Pages' defaults
# https://help.github.com/articles/using-jekyll-with-pages/#configuration-overrides
safe: true
lsi: false
whitelist: [ jekyll-feed, jekyll-sitemap ]
gems:
  - jekyll-feed
  - jekyll-sitemap
  - org-ruby

compress_html:
  clippings: all

author :
  name : Mykola Nikishov
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
