# GH Pages' defaults
# https://help.github.com/articles/using-jekyll-with-pages/#configuration-overrides
safe: true
lsi: false
whitelist: [ jekyll-feed, jekyll-sitemap ]

kramdown:
  highlighter: rouge

# https://help.github.com/articles/configuring-jekyll-plugins/#default-plugins
plugins: # default
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-titles-from-headings
  # optional
  - jekyll-feed
  # - jekyll-redirect-from
  # - jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-avatar
  # - jemoji
  # - jekyll-mentions
  # - jekyll-include-cache
  # extra
  - org-ruby

exclude:
  - Dockerfile
  - docker-compose.yml
  - Gemfile*

repository: manandbytes/manandbytes.github.com

compress_html:
  clippings: all

title: man | and | bytes
author :
  name : Mykola Nikishov
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
